image: node:6.0
pages:
  cache:
    paths:
    - node_modules/
  script:
  - npm install -g typescript
  - npm install
  - npm run build
  - rm -rf node_modules
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
before_script:
- npm install -g typescript
- npm install
build:
  script:
  - npm run build